### ISSUE TITLE
Review - Joanna McAdams

### ISSUE THREAD

**Issue by Jlmcadams** [cmiller112000/ud-datavis#5]
What do you notice in the visualization?

I first noticed how much easier it was to detect trends when the years flow automatically across. Not having to take my eyes off the data or trend pattern to click on different years gave a better appreciation for gaps in info. To go back and single out a year is also simple to do. 

What questions do you have about the data?
How to keep raw data integrity in check - i.e.: one time meaning a plane pulls away from the gate, or actually takes off? 

What relationships do you notice?

It appears to mostly remain consistently inconsistent. 

What do you think is the main take-away from this visualization?

Very smart, easy to read way to interpret what would normally be a very cumbersome data set. Very good to market / prove on time capabilities to consumer, or investors. 

Is there something you don’t understand in the graphic?

Per airport numbers were a little confusing, but that may be my system may not meet requirements. 

Any Additions Comments:

Very exciting to check this out!

**Comment by cmiller112000** [comment]
Thanks Joey!   good feedback.

I have a new release coming later today or tomorrow that fixes the airport selector and a few other issues (like disappearing data).  Hopefully that will make it clearer.  While I liked the look of the bubble chart, I changed it to a line chart with line markers.  It makes the day to day relationships much clearer.  

Re:  "How to keep raw data integrity in check - i.e.: one time meaning a plane pulls away from the gate, or actually takes off?"

I'm not clear on what you are asking?  The raw data I based this on had multiple 'delay' timings and some (but limited) cause indicators.  However, the data set itself, even filtering down to just these carriers and airports was till almost 2GB, and would never load in the browser using the tools I've been given.  So I decided to just concentrate on the average arrival delay, thinking from a consumer standpoint, that is what most people would care about.  I definitely see where the airlines or regulation industry would care much more on drilling down on specific causes.  Is that what you were referring to?

**Comment by Jlmcadams** [comment]
Yes, that is what I was referring to, and it was more industry related, but given each airline had their own criteria for the definition of on time... Well, what can you do to control that? 

I am really impressed with how you tamed THAT MUCH data in one file. Very nice!
